In [9]:
import pandas as pd
import numpy as np

In [5]:
df_old = pd.read_parquet('../../data-storage/preprocessed/ligue1_1516.parquet')
df_new = pd.read_parquet('../../data-storage/preprocessed/ligue1_2015_2016_test.parquet')

In [6]:
df_old.describe()

,x,y,possession,possession_length,chain_length,match_id,period,player_id,shot_statsbomb_xg,under_pressure,next_x,next_y,next_under_pressure,next_team_id,next_player_id
count,604704.000000,604704.000000,604704.000000,604704.000000,604704.00000,6.047040e+05,604704.000000,604704.000000,4090.000000,162038.0,604704.000000,604704.000000,162117.0,604704.000000,604704.000000
mean,49.647711,33.670683,97.330907,9.238194,5.45180,3.880356e+06,1.489481,26699.625809,0.109281,1.0,49.658388,33.670826,1.0,243.987276,26701.241822
std,22.602500,19.588862,57.253445,9.971952,6.95181,3.229581e+04,0.499890,81010.058446,0.144260,0.0,22.611502,19.591274,0.0,506.200143,81015.125622
min,0.087500,0.085000,2.000000,0.000000,0.00000,3.829413e+06,1.000000,2936.000000,0.000180,1.0,0.087500,0.085000,1.0,129.000000,2936.000000
25%,33.687500,16.490000,48.000000,3.000000,1.00000,3.829509e+06,1.000000,3295.000000,0.028378,1.0,33.687500,16.490000,1.0,134.000000,3295.000000
50%,48.562500,33.405000,96.000000,6.000000,3.00000,3.900570e+06,1.000000,4443.000000,0.057035,1.0,48.562500,33.405000,1.0,140.000000,4443.000000
75%,65.712500,50.830000,146.000000,13.000000,8.00000,3.901169e+06,2.000000,8572.000000,0.121250,1.0,65.712500,50.830000,1.0,146.000000,8572.000000
max,104.912500,67.915000,234.000000,146.000000,146.00000,3.901263e+06,2.000000,403392.000000,0.976663,1.0,104.912500,67.915000,1.0,2736.000000,403392.000000

In [7]:
df_new.describe()

,x,y,possession,possession_length,chain_length,match_id,period,player_id,shot_statsbomb_xg,under_pressure,next_x,next_y,next_under_pressure,next_team_id,next_player_id
count,604704.000000,604704.000000,604704.000000,604704.000000,604704.00000,6.047040e+05,604704.000000,604704.000000,4090.000000,162038.0,604704.000000,604704.000000,162117.0,604704.000000,604704.000000
mean,49.647711,33.670683,97.330907,9.238194,5.45180,3.880356e+06,1.489481,26699.625809,0.109281,1.0,49.658388,33.670826,1.0,243.987276,26701.241822
std,22.602500,19.588862,57.253445,9.971952,6.95181,3.229581e+04,0.499890,81010.058446,0.144260,0.0,22.611502,19.591274,0.0,506.200143,81015.125622
min,0.087500,0.085000,2.000000,0.000000,0.00000,3.829413e+06,1.000000,2936.000000,0.000180,1.0,0.087500,0.085000,1.0,129.000000,2936.000000
25%,33.687500,16.490000,48.000000,3.000000,1.00000,3.829509e+06,1.000000,3295.000000,0.028378,1.0,33.687500,16.490000,1.0,134.000000,3295.000000
50%,48.562500,33.405000,96.000000,6.000000,3.00000,3.900570e+06,1.000000,4443.000000,0.057035,1.0,48.562500,33.405000,1.0,140.000000,4443.000000
75%,65.712500,50.830000,146.000000,13.000000,8.00000,3.901169e+06,2.000000,8572.000000,0.121250,1.0,65.712500,50.830000,1.0,146.000000,8572.000000
max,104.912500,67.915000,234.000000,146.000000,146.00000,3.901263e+06,2.000000,403392.000000,0.976663,1.0,104.912500,67.915000,1.0,2736.000000,403392.000000

In [8]:
for col in df_old.columns:
    if col not in df_new.columns:
        print(f"Column '{col}' is missing in the new DataFrame.")
    else:
        old_dtype = df_old[col].dtype
        new_dtype = df_new[col].dtype
        if old_dtype != new_dtype:
            print(f"Column '{col}' has different data types: old={old_dtype}, new={new_dtype}.")

In [10]:
for col in df_old.columns:
    if col not in df_new.columns:
        print(f"Column '{col}' is missing in the new DataFrame.")
    else:
        equal = np.all(df_old[col].values == df_new[col].values)
        if not equal:
            print(f"Column '{col}' has different values.")

Column 'shot_statsbomb_xg' has different values.
Column 'under_pressure' has different values.
Column 'next_under_pressure' has different values.