# WARNING

The authors have become aware that there have been changes in the StatsBomb Open Data set. Consequently, not all 2442 matches used in the paper are still available. The methods still work with a bit less data, although there might be small differences in the exact results. For other questions, feel free to contact the authors.
______________________________________________________________________________________________________________
<br><br>

In [2]:
from statsbombpy import sb
import warnings
import pandas as pd

from datadownloader import DataDownloader
from datasetcreator import columns_to_keep, DataSetCreator

# Download all games

In [3]:
# Call statsbombpy API to get all free competitions
free_comps = sb.competitions()
free_comps.head()

c:\Users\kwvanarem\Documents\GitHub\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,None,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882

In [4]:
free_comps.head(10)

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,None,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
5,16,2,Europe,Champions League,male,False,False,2016/2017,2024-02-13T02:37:32.205154,2021-06-13T16:17:31.694,None,2024-02-13T02:37:32.205154
6,16,27,Europe,Champions League,male,False,False,2015/2016,2024-06-12T07:45:38.786894,2021-06-13T16:17:31.694,None,2024-06-12T07:45:38.786894
7,16,26,Europe,Champions League,male,False,False,2014/2015,2024-02-12T12:49:54.914228,2021-06-13T16:17:31.694,None,2024-02-12T12:49:54.914228
8,16,25,Europe,Champions League,male,False,False,2013/2014,2024-02-12T12:48:48.479157,2021-06-13T16:17:31.694,None,2024-02-12T12:48:48.479157
9,16,24,Europe,Champions League,male,False,False,2012/2013,2024-02-12T12:47:34.340413,2021-06-13T16:17:31.694,None,2024-02-12T12:47:34.340413

In [5]:
free_comps

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-11-15T23:17:41.827093,2025-11-15T23:17:41.827093,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2026-05-12T21:18:08.827431,2026-05-02T02:07:18.902396,2026-05-02T02:07:18.902396,2026-05-12T21:18:08.827431
3,16,4,Europe,Champions League,male,False,False,2018/2019,2026-05-15T15:54:04.598614,2021-06-13T16:17:31.694,None,2026-05-15T15:54:04.598614
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
75,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2026-04-11T12:48:10.012987,2021-06-13T16:17:31.694,None,2026-04-11T12:48:10.012987
76,53,315,Europe,UEFA Women's Euro,female,False,True,2025,2026-04-27T22:02:42.690507,2026-04-27T22:03:28.087062,2026-04-27T22:03:28.087062,2026-04-27T22:02:42.690507
77,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2026-05-05T03:03:04.199896,2026-05-05T03:05:32.480837,2026-05-05T03:05:32.480837,2026-05-05T03:03:04.199896
78,72,107,International,Women's World Cup,female,False,True,2023,2026-05-03T13:51:31.021141,2026-05-03T13:55:52.303219,2026-05-03T13:55:52.303219,2026-05-03T13:51:31.021141
79,72,30,International,Women's World Cup,female,False,True,2019,2026-05-15T15:31:40.299642,2021-06-13T16:17:31.694,None,2026-05-15T15:31:40.299642

In [4]:
competition_ids = [
    11, # LaLiga
    2, # Premier League
    12, # Serie A
    7, # Ligue 1
    9, # Bundesliga
]

In [ ]:
warnings.filterwarnings("ignore", message="credentials were not supplied")
for competition_id in competition_ids:
    free_seasons = free_comps[free_comps['competition_id'] == competition_id]
    downloader = DataDownloader(
        free_seasons, 
        directory='..\\..\\data-storage\\raw\\top_5_leagues',
        )
    downloader.download_store_seasons()

2020_2021

100%|██████████| 35/35 [00:22<00:00,  1.57it/s]

Downloaded, processed, and stored all available events of La Liga (2020/2021) in 0.38 minutes.
2019_2020

100%|██████████| 33/33 [00:20<00:00,  1.58it/s]

Downloaded, processed, and stored all available events of La Liga (2019/2020) in 0.35 minutes.
2018_2019

100%|██████████| 34/34 [00:21<00:00,  1.61it/s]

Downloaded, processed, and stored all available events of La Liga (2018/2019) in 0.36 minutes.
2017_2018

100%|██████████| 36/36 [00:22<00:00,  1.63it/s]

Downloaded, processed, and stored all available events of La Liga (2017/2018) in 0.37 minutes.
2016_2017

100%|██████████| 34/34 [00:20<00:00,  1.69it/s]

Downloaded, processed, and stored all available events of La Liga (2016/2017) in 0.34 minutes.
2015_2016

100%|██████████| 380/380 [03:48<00:00,  1.66it/s]

Downloaded, processed, and stored all available events of La Liga (2015/2016) in 3.82 minutes.
2014_2015

100%|██████████| 38/38 [00:25<00:00,  1.50it/s]

Downloaded, processed, and stored all available events of La Liga (2014/2015) in 0.43 minutes.
2013_2014

100%|██████████| 31/31 [00:21<00:00,  1.42it/s]

Downloaded, processed, and stored all available events of La Liga (2013/2014) in 0.37 minutes.
2012_2013

100%|██████████| 32/32 [00:22<00:00,  1.39it/s]

Downloaded, processed, and stored all available events of La Liga (2012/2013) in 0.39 minutes.
2011_2012

100%|██████████| 37/37 [00:23<00:00,  1.55it/s]

Downloaded, processed, and stored all available events of La Liga (2011/2012) in 0.40 minutes.
2010_2011

100%|██████████| 33/33 [00:21<00:00,  1.55it/s]

Downloaded, processed, and stored all available events of La Liga (2010/2011) in 0.36 minutes.
2009_2010

100%|██████████| 35/35 [00:22<00:00,  1.57it/s]

Downloaded, processed, and stored all available events of La Liga (2009/2010) in 0.38 minutes.
2008_2009

100%|██████████| 31/31 [00:18<00:00,  1.64it/s]

Downloaded, processed, and stored all available events of La Liga (2008/2009) in 0.32 minutes.
2007_2008

100%|██████████| 28/28 [00:17<00:00,  1.58it/s]

Downloaded, processed, and stored all available events of La Liga (2007/2008) in 0.30 minutes.
2006_2007

100%|██████████| 26/26 [00:17<00:00,  1.52it/s]

Downloaded, processed, and stored all available events of La Liga (2006/2007) in 0.29 minutes.
2005_2006

100%|██████████| 17/17 [00:10<00:00,  1.62it/s]

Downloaded, processed, and stored all available events of La Liga (2005/2006) in 0.18 minutes.
2004_2005

100%|██████████| 7/7 [00:03<00:00,  1.85it/s]

Downloaded, processed, and stored all available events of La Liga (2004/2005) in 0.07 minutes.
1973_1974

100%|██████████| 1/1 [00:00<00:00,  1.67it/s]

Downloaded, processed, and stored all available events of La Liga (1973/1974) in 0.01 minutes.
2015_2016

100%|██████████| 380/380 [03:52<00:00,  1.63it/s]

Downloaded, processed, and stored all available events of Premier League (2015/2016) in 3.88 minutes.
2003_2004

100%|██████████| 38/38 [00:23<00:00,  1.62it/s]

Downloaded, processed, and stored all available events of Premier League (2003/2004) in 0.40 minutes.
2015_2016

100%|██████████| 380/380 [03:44<00:00,  1.70it/s]

Downloaded, processed, and stored all available events of Serie A (2015/2016) in 3.74 minutes.
1986_1987

100%|██████████| 1/1 [00:00<00:00,  1.88it/s]

Downloaded, processed, and stored all available events of Serie A (1986/1987) in 0.01 minutes.
2022_2023

100%|██████████| 32/32 [00:20<00:00,  1.57it/s]

Downloaded, processed, and stored all available events of Ligue 1 (2022/2023) in 0.34 minutes.
2021_2022

100%|██████████| 26/26 [00:16<00:00,  1.62it/s]

Downloaded, processed, and stored all available events of Ligue 1 (2021/2022) in 0.27 minutes.
2015_2016

100%|██████████| 377/377 [03:41<00:00,  1.70it/s]

Downloaded, processed, and stored all available events of Ligue 1 (2015/2016) in 3.70 minutes.
2023_2024

100%|██████████| 34/34 [00:19<00:00,  1.71it/s]

Downloaded, processed, and stored all available events of 1. Bundesliga (2023/2024) in 0.34 minutes.
2015_2016

100%|██████████| 306/306 [02:54<00:00,  1.76it/s]

Downloaded, processed, and stored all available events of 1. Bundesliga (2015/2016) in 2.91 minutes.

In [ ]:
# Select UEFA Euros 2020
free_seasons = free_comps[free_comps['season_id'] == 43]
downloader = DataDownloader(
    free_seasons, 
    directory='..\\..\\data-storage\\raw\\euros_2020',
    )
downloader.download_store_seasons()

2020

100%|██████████| 51/51 [00:32<00:00,  1.59it/s]

Downloaded, processed, and stored all available events of UEFA Euro (2020) in 0.54 minutes.

# Create data set

In [ ]:
data_set_creator = DataSetCreator(
    ['type', 'x', 'y', 'under_pressure', 'team_id', 'player_id'],
    storage_directory='./',
)
data_set_creator.create_data_set(
    '../../data-storage/raw/top_5_leagues/', 
    '../../data-storage/preprocessed/top_5_leagues.parquet',
    )

Processing files: 100%|██████████| 2442/2442 [3:25:32<00:00,  5.05s/it]

In [ ]:
data_set_creator = DataSetCreator(
    ['type', 'x', 'y', 'under_pressure', 'team_id', 'player_id'],
    storage_directory='./',
)
data_set_creator.create_data_set(
    r'../../data-storage/raw/top_5_leagues/7-Ligue 1/27-2015_2016/', 
    '../../data-storage/preprocessed/ligue1_1516.parquet',
    )

Processing files: 100%|██████████| 377/377 [06:20<00:00,  1.01s/it]

In [ ]:
data_set_creator = DataSetCreator(
    ['type', 'x', 'y', 'under_pressure', 'team_id', 'player_id'],
    storage_directory='./',
)
data_set_creator.create_data_set(
    '../../data-storage/raw/euros_2020/', 
    '../../data-storage/preprocessed/euros_2020.parquet',
    )

Processing files: 100%|██████████| 51/51 [00:17<00:00,  2.92it/s]

In [ ]:
df_events = pd.read_parquet(
    '../../data-storage/preprocessed/top_5_leagues.parquet', 
    engine='fastparquet',
    )

df_events['shot'] = ~df_events['shot_outcome'].isna()
df_events['goal'] = df_events['shot_outcome'] == 'Goal'

df_events.drop(columns=['id', 'shot_outcome', 'possession'], inplace=True)
df_size_bytes = df_events.memory_usage(deep=True).sum()
df_size_mb = df_size_bytes / (1024 ** 2)  # Convert to MB
print(f"DataFrame size: {df_size_mb:.2f} MB")
print(f"DataFrame shape: {df_events.shape}")

DataFrame size: 1287.32 MB
DataFrame shape: (3985659, 22)